import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import AppLayout from "@/components/AppLayout/index";
import "./globals.css";
import React from "react";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

const fontRobotoMono = Roboto_Mono({
    weight: ["400", "500"],
    subsets: ["latin", "cyrillic"]
});

export default function RootLayout({
    children
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="ru">
            <body className={`${fontRobotoMono.className} antialiased`}>
                <AppLayout>{children}</AppLayout>
            </body>
        </html>
    );
}
