import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import React from "react";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const FontInter = Inter({
    weight: ["400", "500"],
    subsets: ["latin", "cyrillic"]
})

const FontRobotoMono = Roboto_Mono({
    weight: ["400", "500"],
    subsets: ["latin", "cyrillic"]
})

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return <html lang="ru">
        <body className={`${FontInter.className} ${FontRobotoMono.className} antialiased`}>
            {children}
        </body>
    </html>
}
